export interface CharmDecoration {
  name:       string
  skill:      string
  skillLevel: number
  slot:       number
}

export const DECORATION_LIST: CharmDecoration[] = [
  { name: "-",      skill: "無し",               skillLevel: 1, slot: 0 },

  { name: "耐火珠", skill: "火耐性",             skillLevel: 1, slot: 1 },
  { name: "耐水珠", skill: "水耐性",             skillLevel: 1, slot: 1 },
  { name: "耐雷珠", skill: "雷耐性",             skillLevel: 1, slot: 1 },
  { name: "耐氷珠", skill: "氷耐性",             skillLevel: 1, slot: 1 },
  { name: "耐龍珠", skill: "龍耐性",             skillLevel: 1, slot: 1 },
  { name: "耐毒珠", skill: "毒耐性",             skillLevel: 1, slot: 1 },
  { name: "耐麻珠", skill: "麻痺耐性",           skillLevel: 1, slot: 1 },
  { name: "耐眠珠", skill: "睡眠耐性",           skillLevel: 1, slot: 1 },
  { name: "耐爆珠", skill: "爆破やられ耐性",     skillLevel: 1, slot: 1 },
  { name: "植学珠", skill: "植生学",             skillLevel: 1, slot: 1 },
  { name: "地学珠", skill: "地質学",             skillLevel: 1, slot: 1 },
  { name: "飛込珠", skill: "飛び込み",           skillLevel: 1, slot: 1 },
  { name: "陽動珠", skill: "陽動",               skillLevel: 1, slot: 1 },
  { name: "泥雪珠", skill: "泥雪耐性",           skillLevel: 1, slot: 1 },
  { name: "節食珠", skill: "満足感",             skillLevel: 1, slot: 1 },
  { name: "無食珠", skill: "腹減り耐性",         skillLevel: 1, slot: 1 },
  { name: "皮剥珠", skill: "剥ぎ取り鉄人",       skillLevel: 1, slot: 1 },
  { name: "防御珠", skill: "防御",               skillLevel: 1, slot: 1 },
  { name: "火炎珠", skill: "火属性攻撃強化",     skillLevel: 1, slot: 1 },
  { name: "流水珠", skill: "水属性攻撃強化",     skillLevel: 1, slot: 1 },
  { name: "雷光珠", skill: "雷属性攻撃強化",     skillLevel: 1, slot: 1 },
  { name: "氷結珠", skill: "氷属性攻撃強化",     skillLevel: 1, slot: 1 },
  { name: "破龍珠", skill: "龍属性攻撃強化",     skillLevel: 1, slot: 1 },
  { name: "爆師珠", skill: "ボマー",             skillLevel: 1, slot: 1 },
  { name: "滑走珠", skill: "滑走強化",           skillLevel: 1, slot: 1 },
  { name: "毒珠",   skill: "毒属性強化",         skillLevel: 1, slot: 1 },
  { name: "奪気珠", skill: "スタミナ奪取",       skillLevel: 1, slot: 1 },
  { name: "鼓笛珠", skill: "笛吹き名人",         skillLevel: 1, slot: 1 },
  { name: "早復珠", skill: "回復速度",           skillLevel: 1, slot: 1 },
  { name: "研磨珠", skill: "砥石使用高速化",     skillLevel: 1, slot: 1 },
  { name: "防風珠", skill: "風圧耐性",           skillLevel: 1, slot: 1 },
  { name: "耐衝珠", skill: "ひるみ軽減",         skillLevel: 1, slot: 1 },
  { name: "点射珠", skill: "ブレ抑制",           skillLevel: 1, slot: 1 },
  { name: "耐絶珠", skill: "気絶耐性",           skillLevel: 1, slot: 1 },
  { name: "早填珠", skill: "装填速度",           skillLevel: 1, slot: 1 },
  { name: "抑反珠", skill: "反動軽減",           skillLevel: 1, slot: 1 },

  { name: "逆境珠", skill: "不屈",               skillLevel: 1, slot: 2 },
  { name: "乗慣珠", skill: "乗り名人",           skillLevel: 1, slot: 2 },
  { name: "体術珠", skill: "体術",               skillLevel: 1, slot: 2 },
  { name: "治癒珠", skill: "体力回復量UP",       skillLevel: 1, slot: 2 },
  { name: "持続珠", skill: "アイテム使用強化",   skillLevel: 1, slot: 2 },
  { name: "翔蟲珠", skill: "翔蟲使い",           skillLevel: 1, slot: 2 },
  { name: "壁走珠", skill: "壁面移動",           skillLevel: 1, slot: 2 },
  { name: "加護珠", skill: "精霊の加護",         skillLevel: 1, slot: 2 },
  { name: "早食珠", skill: "早食い",             skillLevel: 1, slot: 2 },
  { name: "耐属珠", skill: "属性やられ耐性",     skillLevel: 1, slot: 2 },
  { name: "重撃珠", skill: "破壊王",             skillLevel: 1, slot: 2 },
  { name: "友愛珠", skill: "広域化",             skillLevel: 1, slot: 2 },
  { name: "KO珠",   skill: "KO術",               skillLevel: 1, slot: 2 },
  { name: "速納珠", skill: "納刀術",             skillLevel: 1, slot: 2 },
  { name: "回避珠", skill: "回避性能",           skillLevel: 1, slot: 2 },
  { name: "跳躍珠", skill: "回避距離UP",         skillLevel: 1, slot: 2 },
  { name: "抜打珠", skill: "抜刀術【力】",       skillLevel: 1, slot: 2 },
  { name: "泡沫珠", skill: "泡沫の舞",           skillLevel: 1, slot: 2 },
  { name: "逆襲珠", skill: "逆襲",               skillLevel: 1, slot: 2 },
  { name: "耐震珠", skill: "耐震",               skillLevel: 1, slot: 2 },
  { name: "鈍器珠", skill: "鈍器使い",           skillLevel: 1, slot: 2 },
  { name: "速変珠", skill: "高速変形",           skillLevel: 1, slot: 2 },
  { name: "達人珠", skill: "見切り",             skillLevel: 1, slot: 2 },
  { name: "攻撃珠", skill: "攻撃",               skillLevel: 1, slot: 2 },
  { name: "渾身珠", skill: "渾身",               skillLevel: 1, slot: 2 },
  { name: "昂揚珠", skill: "強化持続",           skillLevel: 1, slot: 2 },
  { name: "早気珠", skill: "スタミナ急速回復",   skillLevel: 1, slot: 2 },
  { name: "鉄壁珠", skill: "ガード性能",         skillLevel: 1, slot: 2 },
  { name: "強壁珠", skill: "ガード強化",         skillLevel: 1, slot: 2 },
  { name: "増弾珠", skill: "砲弾装填",           skillLevel: 1, slot: 2 },
  { name: "特射珠", skill: "特殊射撃強化",       skillLevel: 1, slot: 2 },
  { name: "底力珠", skill: "火事場力",           skillLevel: 1, slot: 2 },
  { name: "心眼珠", skill: "心眼",               skillLevel: 1, slot: 2 },
  { name: "短縮珠", skill: "集中",               skillLevel: 1, slot: 2 },
  { name: "強走珠", skill: "ランナー",           skillLevel: 1, slot: 2 },
  { name: "砲術珠", skill: "砲術",               skillLevel: 1, slot: 2 },
  { name: "属会珠", skill: "会心撃【属性】",     skillLevel: 1, slot: 2 },
  { name: "射法珠", skill: "弾導強化",           skillLevel: 1, slot: 2 },
  { name: "超心珠", skill: "超会心",             skillLevel: 1, slot: 2 },
  { name: "痛撃珠", skill: "弱点特効",           skillLevel: 1, slot: 2 },
  { name: "挑戦珠", skill: "挑戦者",             skillLevel: 1, slot: 2 },
  { name: "無傷珠", skill: "フルチャージ",       skillLevel: 1, slot: 2 },
  { name: "逆上珠", skill: "逆恨み",             skillLevel: 1, slot: 2 },
  { name: "窮地珠", skill: "死中に活",           skillLevel: 1, slot: 2 },
  { name: "全開珠", skill: "力の解放",           skillLevel: 1, slot: 2 },
  { name: "麻痺珠", skill: "麻痺属性強化",       skillLevel: 1, slot: 2 },
  { name: "睡眠珠", skill: "睡眠属性強化",       skillLevel: 1, slot: 2 },
  { name: "爆破珠", skill: "爆破属性強化",       skillLevel: 1, slot: 2 },
  { name: "剛刃珠", skill: "剛刃研磨",           skillLevel: 1, slot: 2 },
  { name: "斬鉄珠", skill: "業物",               skillLevel: 1, slot: 2 },
  { name: "節弾珠", skill: "弾丸節約",           skillLevel: 1, slot: 2 },
  { name: "達芸珠", skill: "達人芸",             skillLevel: 1, slot: 2 },

  { name: "防音珠", skill: "耳栓",               skillLevel: 1, slot: 3 },
  { name: "抜刀珠", skill: "抜刀術【技】",       skillLevel: 1, slot: 3 },
  { name: "茸好珠", skill: "キノコ大好き",       skillLevel: 1, slot: 3 },
  { name: "守勢珠", skill: "攻めの守勢",         skillLevel: 1, slot: 3 },
  { name: "装填珠", skill: "装填拡張",           skillLevel: 1, slot: 3 },
  { name: "強弾珠", skill: "通常弾・連射矢強化", skillLevel: 1, slot: 3 },
  { name: "貫通珠", skill: "貫通弾・貫通矢強化", skillLevel: 1, slot: 3 },
  { name: "散弾珠", skill: "散弾・拡散矢強化",   skillLevel: 1, slot: 3 },
  { name: "速射珠", skill: "速射強化",           skillLevel: 1, slot: 3 },
  { name: "強跳珠", skill: "ジャンプ鉄人",       skillLevel: 1, slot: 3 },
  { name: "鬼火珠", skill: "鬼火纏",             skillLevel: 1, slot: 3 },
  { name: "運気珠", skill: "幸運",               skillLevel: 1, slot: 3 },
  { name: "匠珠",   skill: "匠",                 skillLevel: 1, slot: 3 },


  // added in sunbreak
  { name: "壁翔珠", skill: "壁面移動【翔】",    skillLevel: 1, slot: 1 },

  { name: "火炎珠Ⅱ", skill: "火属性攻撃強化",   skillLevel: 2, slot: 2 },
  { name: "流水珠Ⅱ", skill: "水属性攻撃強化",   skillLevel: 2, slot: 2 },
  { name: "雷光珠Ⅱ", skill: "雷属性攻撃強化",   skillLevel: 2, slot: 2 },
  { name: "氷結珠Ⅱ", skill: "氷属性攻撃強化",   skillLevel: 2, slot: 2 },
  { name: "破龍珠Ⅱ", skill: "龍属性攻撃強化",   skillLevel: 2, slot: 2 },
  { name: "刃鱗珠",  skill: "刃鱗磨き",         skillLevel: 1, slot: 2 },
  { name: "防御珠Ⅱ", skill: "防御",             skillLevel: 2, slot: 2 },

  { name: "合気珠",  skill: "合気",             skillLevel: 1, slot: 3 },
  { name: "息吹珠",  skill: "疾之息吹",         skillLevel: 1, slot: 3 },
  { name: "火炎珠Ⅲ", skill: "火属性攻撃強化",   skillLevel: 3, slot: 3 },
  { name: "流水珠Ⅲ", skill: "水属性攻撃強化",   skillLevel: 3, slot: 3 },
  { name: "雷光珠Ⅲ", skill: "雷属性攻撃強化",   skillLevel: 3, slot: 3 },
  { name: "氷結珠Ⅲ", skill: "氷属性攻撃強化",   skillLevel: 3, slot: 3 },
  { name: "破龍珠Ⅲ", skill: "龍属性攻撃強化",   skillLevel: 3, slot: 3 },
  { name: "鉄壁珠Ⅱ", skill: "ガード性能",       skillLevel: 2, slot: 3 },
  { name: "防御珠Ⅲ", skill: "防御",             skillLevel: 3, slot: 3 },
  { name: "友愛珠Ⅲ", skill: "広域化",           skillLevel: 3, slot: 3 },

  { name: "泡沫珠Ⅱ", skill: "泡沫の舞",         skillLevel: 2, slot: 4 },
  { name: "運気珠Ⅱ", skill: "幸運",             skillLevel: 2, slot: 4 },
  { name: "鬼火珠Ⅱ", skill: "鬼火纏",           skillLevel: 2, slot: 4 },
  { name: "回避珠Ⅱ", skill: "回避性能",         skillLevel: 2, slot: 4 },
  { name: "翔蟲珠Ⅱ", skill: "翔蟲使い",         skillLevel: 2, slot: 4 },
  { name: "加護珠Ⅱ", skill: "精霊の加護",       skillLevel: 2, slot: 4 },
  { name: "茸好珠Ⅱ", skill: "キノコ大好き",     skillLevel: 2, slot: 4 },
  { name: "強弓珠",  skill: "弓溜め段階解放",   skillLevel: 1, slot: 4 },
  { name: "強走珠Ⅱ", skill: "ランナー",         skillLevel: 2, slot: 4 },
  { name: "強壁珠Ⅱ", skill: "ガード強化",       skillLevel: 2, slot: 4 },
  { name: "研磨珠Ⅲ", skill: "砥石使用高速化",   skillLevel: 3, slot: 4 },
  { name: "KO珠Ⅱ",   skill: "KO術",             skillLevel: 2, slot: 4 },
  { name: "昂揚珠Ⅱ", skill: "強化持続",         skillLevel: 2, slot: 4 },
  { name: "射法珠Ⅱ", skill: "弾導強化",         skillLevel: 2, slot: 4 },
  { name: "植学珠Ⅲ", skill: "植生学",           skillLevel: 3, slot: 4 },
  { name: "心眼珠Ⅱ", skill: "心眼",             skillLevel: 2, slot: 4 },
  { name: "持続珠Ⅲ", skill: "アイテム使用強化", skillLevel: 3, slot: 4 },
  { name: "節食珠Ⅲ", skill: "満足感",           skillLevel: 3, slot: 4 },
  { name: "早気珠Ⅱ", skill: "スタミナ急速回復", skillLevel: 2, slot: 4 },
  { name: "早食珠Ⅱ", skill: "早食い",           skillLevel: 2, slot: 4 },
  { name: "早復珠Ⅲ", skill: "回復速度",         skillLevel: 3, slot: 4 },
  { name: "属会珠Ⅱ", skill: "会心撃【属性】",   skillLevel: 2, slot: 4 },
  { name: "耐火珠Ⅲ", skill: "火耐性",           skillLevel: 3, slot: 4 },
  { name: "耐衝珠Ⅲ", skill: "ひるみ軽減",       skillLevel: 3, slot: 4 },
  { name: "耐振珠Ⅱ", skill: "耐震",             skillLevel: 2, slot: 4 },
  { name: "体術珠Ⅱ", skill: "体術",             skillLevel: 2, slot: 4 },
  { name: "耐水珠Ⅲ", skill: "水耐性",           skillLevel: 3, slot: 4 },
  { name: "耐絶珠Ⅲ", skill: "気絶耐性",         skillLevel: 3, slot: 4 },
  { name: "耐属珠Ⅱ", skill: "属性やられ耐性",   skillLevel: 2, slot: 4 },
  { name: "耐氷珠Ⅲ", skill: "氷耐性",           skillLevel: 3, slot: 4 },
  { name: "耐雷珠Ⅲ", skill: "雷耐性",           skillLevel: 3, slot: 4 },
  { name: "耐龍珠Ⅲ", skill: "龍耐性",           skillLevel: 3, slot: 4 },
  { name: "短縮珠Ⅱ", skill: "集中",             skillLevel: 2, slot: 4 },
  { name: "奪気珠Ⅲ", skill: "スタミナ奪取",     skillLevel: 3, slot: 4 },
  { name: "地学珠Ⅲ", skill: "地質学",           skillLevel: 3, slot: 4 },
  { name: "治癒珠Ⅱ", skill: "体力回復量UP",     skillLevel: 2, slot: 4 },
  { name: "跳躍珠Ⅱ", skill: "回避距離UP",       skillLevel: 2, slot: 4 },
  { name: "点射珠Ⅱ", skill: "ブレ抑制",         skillLevel: 2, slot: 4 },
  { name: "爆師珠Ⅲ", skill: "ボマー",           skillLevel: 3, slot: 4 },
  { name: "抜刀珠Ⅱ", skill: "抜刀術【技】",     skillLevel: 2, slot: 4 },
  { name: "抜打珠Ⅱ", skill: "抜刀術【力】",     skillLevel: 2, slot: 4 },
  { name: "壁走珠Ⅲ", skill: "壁面移動",         skillLevel: 3, slot: 4 },
  { name: "防音珠Ⅱ", skill: "耳栓",             skillLevel: 2, slot: 4 },
  { name: "防御珠Ⅴ", skill: "防御",             skillLevel: 5, slot: 4 },
  { name: "防風珠Ⅲ", skill: "風圧耐性",         skillLevel: 3, slot: 4 },
  { name: "無食珠Ⅲ", skill: "腹減り耐性",       skillLevel: 3, slot: 4 },
  { name: "友愛珠Ⅳ", skill: "広域化",           skillLevel: 4, slot: 4 },
];
